server:
  port: 9443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: keystore
    keyStoreType: PKCS12
    keyAlias: tomcat

spring:
  application:
    name: new-client
  boot:
    admin:
      client:
        url: http://localhost:9090

management:
  endpoints:
    web:
      exposure:
        include: "*"